name: Deploy React App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # ⬇️ Build শুরুর আগেই .env তৈরি করুন
      - name: Create .env file
        run: |
          echo "VITE_API_BASE=${{ secrets.VITE_API_BASE }}" > .env
        # একাধিক ভ্যারিয়েবল হলে:
        # run: |
        #   cat > .env << 'EOF'
        #   VITE_API_BASE=${{ secrets.VITE_API_BASE }}
        #   VITE_SOME_KEY=${{ secrets.VITE_SOME_KEY }}
        #   EOF

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          CI: true
        run: npm run build

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist/**"
          target: "${{ secrets.VPS_PATH }}/"
          debug: true
